### 멀티 인덱스

In [18]:

import pandas as pd 
import numpy as np

In [19]:
index = [('California', 2000), ('California', 2010),
         ('New York', 2000), ('New York', 2010),
         ('Texas', 2000), ('Texas', 2010)]

index

# 튜플로 넣음
# 각각 꺼낼 땐 숫자로

[('California', 2000),
 ('California', 2010),
 ('New York', 2000),
 ('New York', 2010),
 ('Texas', 2000),
 ('Texas', 2010)]

In [20]:
# 한 번에 꺼낼 때
for x in index :
    print(x)


# 하나씩 꺼낼 때
for x in index :
    print(x[0], x[1])

('California', 2000)
('California', 2010)
('New York', 2000)
('New York', 2010)
('Texas', 2000)
('Texas', 2010)
California 2000
California 2010
New York 2000
New York 2010
Texas 2000
Texas 2010

In [21]:
populations = [33871648, 37253956, 18976457, 19378102, 20851820, 25145561]
populations

[33871648, 37253956, 18976457, 19378102, 20851820, 25145561]

In [22]:
pop = pd.Series(populations, index=index)
pop

# 왜 index=index로 표현하지?
# 결과값 확인
# 인덱스로 populations를 씀
# 시리즈로 묶어줌

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64

In [23]:
pop = pd.Series(populations)
pop

# index 얘기 안 하면 이렇게 나옴

0    33871648
1    37253956
2    18976457
3    19378102
4    20851820
5    25145561
dtype: int64

In [24]:
# 비효율적인 방법

#pop[[i for i in pop.index if i[1]==2000]]
pop[[i for i in pop.index if i == 2000]]

Series([], dtype: int64)

In [25]:
# list comprehension
# 파이썬 복습

# 1. 기존 리스트의 모든 요소에 특정 연산을 적용하여 새 리스트를 만드는 경우
squares = [x**2 for x in range(10)] # [■ for ■ in ◆] 0부터 9까지를 제곱해서 새 리스트에 집어넣어라
print(squares)

words = ['python', 'is', 'awesome']
upper_words = [w.upper() for w in words]
print(upper_words)
#---------------------------------------
# 2. 조건에 맞는 요소만 골라내고 나머지는 버림
evens = [x for x in range(1, 21) if x % 2 == 0] # [■ for ■ in ◆ if ●]
print(evens)

fruits = ['apple', 'banana', 'cherry', 'kiwi', 'mango']
a_fruits = [f for f in fruits if 'a' in f]
print(a_fruits)
#---------------------------------
# 3. 조건에 의해서 새로운 리스트 만들기
numbers = [1, 2, 3, 4, 5]
labels = ['Even' if x % 2 == 0 else 'Odd' for x in numbers] # [♣ if ■ for ■ in ◆] # 이거 이해 못함 저 클로버 위치
# for x in numbers 이 x를 조건으로(if x % 2 == 0) 사용
print(labels)
#---------------------
# 4. for안에 또 다른 for
matrix = [[1, 2], [3, 4], [5, 6]]
flat = [num for row in matrix for num in row]

print(flat)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
['PYTHON', 'IS', 'AWESOME']
[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
['apple', 'banana', 'mango']
['Odd', 'Even', 'Odd', 'Even', 'Odd']
[1, 2, 3, 4, 5, 6]

In [26]:
matrix = [[1, 2], [3, 4], [5, 6]]

for row in matrix:
    for num in row:
        print(num)

# 두 for를 한 줄에 쓰면
# for row in matrix for num in row

# 마지막 num을 앞쪽에 < 왜그런데요
# num for row in matrix for num in row

1
2
3
4
5
6

In [27]:
# 5. dictionary comprehension

square_dict = {x: x**2 for x in range(5)}
print(square_dict)

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16}

In [28]:
# pandas MultiIndex

In [29]:
print(index)

[('California', 2000), ('California', 2010), ('New York', 2000), ('New York', 2010), ('Texas', 2000), ('Texas', 2010)]

In [30]:
print(type(index))
# 시리즈 만들 때, INDEX를 시리즈로 줬어도 원래 값은 리스트다.

<class 'list'>

In [31]:
# index (타입 list) -> index_multi (타입 multiindex)
# 1 abcd(1)

index_multi = pd.MultiIndex.from_tuples(index)
index_multi

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           )

In [32]:
# 1. pd.MultiIndex.from_product
# from_product 
# 리스트를 넘겨줘서, 짝을 지어라 (조합은 얘가 알아서 해줌)
# 별도의 리스트
states = ['California', 'New York', 'Texas']
years = [2000, 2010]

index_multi = pd.MultiIndex.from_product([states, years], names=['state', 'year'])

print(index_multi)

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           names=['state', 'year'])

In [33]:
# 리스트의 리스트
# from_arrays : 하나하나 떠먹여줘야 한다 * arrays 참고
# 배열 크기 같아야 함.
arrays = [
    ['California', 'California', 'New York', 'New York', 'Texas', 'Texas'],
    [2000, 2010, 2000, 2010, 2000, 2010]
]

index_multi = pd.MultiIndex.from_arrays(arrays, names=['state', 'year'])
print(index_multi)

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           names=['state', 'year'])

In [34]:
# 데이터프레임의 컬럼을 사용
# from_frame 컬럼을 멀티 인덱스로
df_info = pd.DataFrame({
    'state': ['California', 'California', 'New York', 'New York', 'Texas', 'Texas'],
    'year': [2000, 2010, 2000, 2010, 2000, 2010]
})

index_multi = pd.MultiIndex.from_frame(df_info)
print(index_multi)

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           names=['state', 'year'])

In [35]:
# set_index 사용
# 컬럼을 인덱스로 (이번에는 여러개 설정)
data = {
    'state': ['California', 'California', 'New York', 'New York', 'Texas', 'Texas'],
    'year': [2000, 2010, 2000, 2010, 2000, 2010],
    'pop': [33.8, 37.2, 18.9, 19.3, 20.8, 25.1]
}
df = pd.DataFrame(data)
df
# 셀 분리 (컨트롤 시프트 -)

        state  year   pop
0  California  2000  33.8
1  California  2010  37.2
2    New York  2000  18.9
3    New York  2010  19.3
4       Texas  2000  20.8
5       Texas  2010  25.1

In [36]:

df_multi = df.set_index(['state', 'year']) # 인덱스 여럿을 리스트로 지정
# print(df_multi)
df_multi

                  pop
state      year
California 2000  33.8
           2010  37.2
New York   2000  18.9
           2010  19.3
Texas      2000  20.8
           2010  25.1

In [37]:
# 현재 pop
pop

0    33871648
1    37253956
2    18976457
3    19378102
4    20851820
5    25145561
dtype: int64

In [38]:
index_multi

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           names=['state', 'year'])

In [39]:
# reindex (이미 있는 건 버리고 새로운 걸로 갈아끼움)
# index 타입은 list 였고, index_multi는 타입이 multiindex임
# index의 타입 index, multiindex 2 종류가 있음.
# index는 1개, multiindex는 2개 이상
# index는 리스트도 할 수 있다.
pop_multi = pop.reindex(index_multi)
pop_multi

state       year
California  2000   NaN
            2010   NaN
New York    2000   NaN
            2010   NaN
Texas       2000   NaN
            2010   NaN
dtype: float64

In [40]:
type(pop_multi)
# pop_multi의 타입은 Series

pandas.Series

In [41]:
# 비효율적인 방법
# pop[[i for i in pop.index if i[1]==2000]]

pop_multi[:, 2000]
# pop_multi의 타입은 Series이기 때문에 컬럼이 하나밖에 없음 < ???
# pandas는 pop_multi[:, 2000]을 보고 멀티인덱스라고 판단 < 컬럼이 1개밖에 없는데 , 를 썼으니 인덱스라고 판단함

# pop_multi가 데이터프레임인 경우 pop_multi[:, 2000]는 에러 발생
# 왜냐, 데이터프레임은 컬럼이 여러개임. 따라서 이땐 loc, iloc를 씀 
# df[행, 열]은 없음 (데이터프레임은 []하나로 안 됨.), df.loc[], df.iloc[]를 사용해야 함

state
California   NaN
New York     NaN
Texas        NaN
dtype: float64

In [42]:
# 정리

import pandas as pd

data = {
    'state': ['California', 'New York', 'Texas', 'Florida'],
    'year': [2000, 2010, 2000, 2010],
    'pop': [33.8, 37.2, 20.8, 18.8]
}
df = pd.DataFrame(data)
df

        state  year   pop
0  California  2000  33.8
1    New York  2010  37.2
2       Texas  2000  20.8
3     Florida  2010  18.8

In [43]:
# 1. df[]는 기본적으로 컬럼 선택 → 컬럼 타입은 대체로 문자열

col_state = df['state']
print(col_state)

print("-"*50)

# 리스트를 넣어서 여러 컬럼 선택
cols = df[['state', 'pop']]
print(cols)

0    California
1      New York
2         Texas
3       Florida
Name: state, dtype: str
--------------------------------------------------
        state   pop
0  California  33.8
1    New York  37.2
2       Texas  20.8
3     Florida  18.8

In [44]:
# 2. df[]에 :를 사용하면 행 선택

rows = df[0:2]
print(rows)

# df[]에 쉼표가 없다
# 1. 슬라이스 → 행 선택
# 2.   컬럼명 → 열 선택, [컬럼1, 컬럼 2, ...]은 쉼표가 아니라 단일 리스트를 넘긴 것

        state  year   pop
0  California  2000  33.8
1    New York  2010  37.2

In [45]:
# 3. 불리언 마스크를 사용하면 '행' 선택

mask = df['pop'] > 30 #(마스크)
print(df[mask])

        state  year   pop
0  California  2000  33.8
1    New York  2010  37.2

In [46]:
# 컬럼 이름을 알려주지 않음

df = pd.DataFrame([[10, 20], [30, 40]])
# pandas가 디폴트 컬럼 이름 0, 1, 2, ...을 사용
# 이 경우 컬럼명은 숫자 타입에 해당
print(df)
print('-'*100)
print(df[0]) 

# print(df['0']) # KeyError: '0'
# df[0] < 이거 컬럼 선택인데 오류 안 나는 이유는 컬럼값이 0이라서 (아까 그거는 컬럼명 따로 지정해줘서 오류남)

    0   1
0  10  20
1  30  40
----------------------------------------------------------------------------------------------------
0    10
1    30
Name: 0, dtype: int64

In [47]:
# pd.Series를 데이터프레임에 끼워넣기

pop_multi 
#얘는 이미 인덱스 붙어있음 (state,year)

#타입 시리즈

state       year
California  2000   NaN
            2010   NaN
New York    2000   NaN
            2010   NaN
Texas       2000   NaN
            2010   NaN
dtype: float64

In [48]:
# index를 별도 지정하지 않아, total의 인덱스가 그 역할을 함.
pop_df = pd.DataFrame({
    'total': pop_multi,
    'under18': [9267089, 9284094, 4687374, 4318033, 5906301, 6879014],
})

pop_df

                 total  under18
state      year
California 2000    NaN  9267089
           2010    NaN  9284094
New York   2000    NaN  4687374
           2010    NaN  4318033
Texas      2000    NaN  5906301
           2010    NaN  6879014

In [49]:
# 인덱스 이름 - 다 만들고 나중에 이름 붙이기
# .rand(행의 개수,열의 개수)
rng = np.random.RandomState(42) # random number generator
rng.rand(6, 3)

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452],
       [0.05808361, 0.86617615, 0.60111501],
       [0.70807258, 0.02058449, 0.96990985],
       [0.83244264, 0.21233911, 0.18182497],
       [0.18340451, 0.30424224, 0.52475643]])

In [50]:

# rng.rand(6, 3)는 난수 생성기(rng)를 사용해서 6행 3열의 2차원 배열을 생성
# 멀티인덱스 알아서 만들어줌. 
# 현재 멀티인덱스에 이름이 없다
df = pd.DataFrame(rng.rand(6, 3), 
                  index = [['A', 'A', 'B', 'B', 'C', 'C'], [1,2,1,2,1,2]],
                  columns = ['col1', 'col2', 'col3']
                  )

df

         col1      col2      col3
A 1  0.431945  0.291229  0.611853
  2  0.139494  0.292145  0.366362
B 1  0.456070  0.785176  0.199674
  2  0.514234  0.592415  0.046450
C 1  0.607545  0.170524  0.065052
  2  0.948886  0.965632  0.808397

In [51]:
df.index.names = ['index1', 'index2']
df

                   col1      col2      col3
index1 index2
A      1       0.431945  0.291229  0.611853
       2       0.139494  0.292145  0.366362
B      1       0.456070  0.785176  0.199674
       2       0.514234  0.592415  0.046450
C      1       0.607545  0.170524  0.065052
       2       0.948886  0.965632  0.808397

In [52]:
# 인덱스 이름 - 만들면서 알려주기
# names = 

index_arr = [['A', 'A', 'B', 'B', 'C', 'C'], [1,2,1,2,1,2]]
index = pd.MultiIndex.from_arrays(index_arr, names = ('index1', 'index2'))
#                                            ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑

df = pd.DataFrame(rng.rand(6,3), 
                  index = index,
                  columns = ['col1', 'col2', 'col3']
                  )

df

                   col1      col2      col3
index1 index2
A      1       0.304614  0.097672  0.684233
       2       0.440152  0.122038  0.495177
B      1       0.034389  0.909320  0.258780
       2       0.662522  0.311711  0.520068
C      1       0.546710  0.184854  0.969585
       2       0.775133  0.939499  0.894827

In [53]:
# 행만 있냐? 컬럼도 있다
# 멀티인덱스를 컬럼도 할 수 있다
row_index = pd.MultiIndex.from_product([[2013, 2014], ['1st', '2nd']], names = ['Year', 'Visit'])
col_index = pd.MultiIndex.from_product([['Bob', 'Guido', 'Sue'], ['HR', 'Temp']], names= ['Patient', 'Data type'])
print(row_index)
print(col_index)

MultiIndex([(2013, '1st'),
            (2013, '2nd'),
            (2014, '1st'),
            (2014, '2nd')],
           names=['Year', 'Visit'])
MultiIndex([(  'Bob',   'HR'),
            (  'Bob', 'Temp'),
            ('Guido',   'HR'),
            ('Guido', 'Temp'),
            (  'Sue',   'HR'),
            (  'Sue', 'Temp')],
           names=['Patient', 'Data type'])

In [54]:
data_hr = np.random.randint(50, 80, 12) # 50부터 79까지의 정수중에서 무작위로 12개 선택
data_temp = 37 + np.random.randn(12) # 평균이 0이고 표준편차가 1인 표준정규분포 random number 12개

data_x = [i for i in zip(data_hr, data_temp)]
data_x

[(np.int32(76), np.float64(38.380711139377986)),
 (np.int32(72), np.float64(37.776484372673856)),
 (np.int32(50), np.float64(38.33319672389537)),
 (np.int32(62), np.float64(36.960316289527356)),
 (np.int32(65), np.float64(38.78238305873679)),
 (np.int32(72), np.float64(36.396895468455895)),
 (np.int32(62), np.float64(35.46573984944787)),
 (np.int32(56), np.float64(37.093958599667786)),
 (np.int32(63), np.float64(35.96313195909528)),
 (np.int32(74), np.float64(37.19854258401425)),
 (np.int32(60), np.float64(37.949979752396814)),
 (np.int32(74), np.float64(37.688802079162386))]

In [55]:
arr = np.array(data_x)
print(arr)

[[76.         38.38071114]
 [72.         37.77648437]
 [50.         38.33319672]
 [62.         36.96031629]
 [65.         38.78238306]
 [72.         36.39689547]
 [62.         35.46573985]
 [56.         37.0939586 ]
 [63.         35.96313196]
 [74.         37.19854258]
 [60.         37.94997975]
 [74.         37.68880208]]

In [56]:
# Reshape 함수 to 4 rows and 6 cols
# 전체 자료값 자리 개수는 같아야 함.
# shape를 바꿈 원래 (12,2) 였는데... 뭘 하든간에 전부 24개기만 하면 됨.
arr_multi = arr.reshape(4,6)
arr_multi

array([[76.        , 38.38071114, 72.        , 37.77648437, 50.        ,
        38.33319672],
       [62.        , 36.96031629, 65.        , 38.78238306, 72.        ,
        36.39689547],
       [62.        , 35.46573985, 56.        , 37.0939586 , 63.        ,
        35.96313196],
       [74.        , 37.19854258, 60.        , 37.94997975, 74.        ,
        37.68880208]])

In [57]:
health_data = pd.DataFrame(arr_multi, columns=col_index, index=row_index)
health_data

Patient      Bob            Guido              Sue
Data type     HR       Temp    HR       Temp    HR       Temp
Year Visit
2013 1st    76.0  38.380711  72.0  37.776484  50.0  38.333197
     2nd    62.0  36.960316  65.0  38.782383  72.0  36.396895
2014 1st    62.0  35.465740  56.0  37.093959  63.0  35.963132
     2nd    74.0  37.198543  60.0  37.949980  74.0  37.688802

In [58]:
health_data['Bob'] #데이터 프레임임

Data type     HR       Temp
Year Visit
2013 1st    76.0  38.380711
     2nd    62.0  36.960316
2014 1st    62.0  35.465740
     2nd    74.0  37.198543

In [59]:
health_data['Bob']['HR'] # Temp 없이 HR만.

Year  Visit
2013  1st      76.0
      2nd      62.0
2014  1st      62.0
      2nd      74.0
Name: HR, dtype: float64

In [60]:
health_data['Bob','HR'] # 레벨이 2개면 따로 쓰거나, 이렇게 한 번에 쓸 수 있음

Year  Visit
2013  1st      76.0
      2nd      62.0
2014  1st      62.0
      2nd      74.0
Name: (Bob, HR), dtype: float64

In [61]:
health_data.loc[2014, ('Bob','HR')] # 튜플로 묶음 (다른 레벨일 때 사용)
# health_data.loc[2014, ['Bob','HR']] # 리스트로 묶음 (다른 레벨일 땐 오류남)(같은 레벨일 때 사용)

# 튜플은 계층을 표현: ('Bob','HR') → 첫 번째 인덱스는 'Bob', 두 번째 인덱스는 'HR'
# 리스트는 단순 나열임 → 첫 번째 인덱스에 'Bob'은 있지만 'HR'는 없음

Visit
1st    62.0
2nd    74.0
Name: (Bob, HR), dtype: float64

In [62]:
health_data.loc[2014, ['Bob','Sue']] # 같은 레벨일 땐, 리스트로 묶음

Patient     Bob              Sue
Data type    HR       Temp    HR       Temp
Visit
1st        62.0  35.465740  63.0  35.963132
2nd        74.0  37.198543  74.0  37.688802