In [84]:

import pandas as pd 
import numpy as np

In [85]:
index = [('California', 2000), ('California', 2010),
         ('New York', 2000), ('New York', 2010),
         ('Texas', 2000), ('Texas', 2010)]

index

[('California', 2000),
 ('California', 2010),
 ('New York', 2000),
 ('New York', 2010),
 ('Texas', 2000),
 ('Texas', 2010)]

In [86]:
populations = [33871648, 37253956, 18976457, 19378102, 20851820, 25145561]
populations

[33871648, 37253956, 18976457, 19378102, 20851820, 25145561]

In [87]:
pop = pd.Series(populations, index=index) #시리즈에도 index가 있다
#pop = pd.Series(populations)
pop

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64

In [88]:
# 비효율적인 방법

pop[[i for i in pop.index if i[1]==2000]]
#[('California',2000),('New York',2000), ('Texas', 2000)]

(California, 2000)    33871648
(New York, 2000)      18976457
(Texas, 2000)         20851820
dtype: int64

In [89]:
# list comprehension

# 1. 기존 리스트의 모든 요소에 특정 연산을 적용하여 새 리스트를 만드는 경우
squares = [x**2 for x in range(10)] #[• for ‣ in ♪ ]
print(squares)

words = ['python', 'is', 'awesome']
upper_words = [w.upper() for w in words]
print(upper_words)

# 2. 조건에 맞는 요소만 골라내고 나머지는 버림
evens = [x for x in range(1, 21) if x % 2 == 0] #[• for ‣ in ♪ if ©]
print(evens)

fruits = ['apple', 'banana', 'cherry', 'kiwi', 'mango']
a_fruits = [f for f in fruits if 'a' in f]
print(a_fruits)

# 3. 조건에 의해서 새로운 리스트 만들기
numbers = [1, 2, 3, 4, 5]
labels = ['Even' if x % 2 == 0 else 'Odd' for x in numbers] #[• if ‣ for ♪ in ©]
print(labels)

# 4. for안에 또 다른 for
matrix = [[1, 2], [3, 4], [5, 6]]
flat = [num for row in matrix for num in row]

print(flat)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
['PYTHON', 'IS', 'AWESOME']
[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
['apple', 'banana', 'mango']
['Odd', 'Even', 'Odd', 'Even', 'Odd']
[1, 2, 3, 4, 5, 6]

In [90]:
matrix = [[1, 2], [3, 4], [5, 6]]

for row in matrix:
    for num in row:
        print(num)

# 두 for를 한 줄에 쓰면
# for row in matrix for num in row

# 마지막 num을 앞쪽에
# num for row in matrix for num in row

1
2
3
4
5
6

In [91]:
# 5. dictionary comprehension

square_dict = {x: x**2 for x in range(5)} #딕셔너리 key x dictionary x값
print(square_dict)

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16}

In [92]:
# pandas MultiIndex

In [93]:
print(index) #인덱스의 타입은 list다

[('California', 2000), ('California', 2010), ('New York', 2000), ('New York', 2010), ('Texas', 2000), ('Texas', 2010)]

In [94]:
print(type(index))

<class 'list'>

In [95]:
# infex -> indev)muti()
index_multi = pd.MultiIndex.from_tuples(index)
index_multi

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           )

In [96]:
# 1. pd.MultiIndex.from_product

# 별도의 리스트
states = ['California', 'New York', 'Texas']
years = [2000, 2010]

index_multi = pd.MultiIndex.from_product([states, years], names=['state', 'year'])
print(index_multi)

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           names=['state', 'year'])

In [97]:
# 리스트의 리스트

arrays = [
    ['California', 'California', 'New York', 'New York', 'Texas', 'Texas'],
    [2000, 2010, 2000, 2010, 2000, 2010]
]

index_multi = pd.MultiIndex.from_arrays(arrays, names=['state', 'year'])
print(index_multi)

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           names=['state', 'year'])

In [98]:
# 데이터프레임의 컬럼을 사용
#데이터  프레임에서 만들겠다
df_info = pd.DataFrame({
    'state': ['California', 'California', 'New York', 'New York', 'Texas', 'Texas'],
    'year': [2000, 2010, 2000, 2010, 2000, 2010]
})

index_multi = pd.MultiIndex.from_frame(df_info)
print(index_multi)

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           names=['state', 'year'])

In [99]:
# set_index 사용

data = {
    'state': ['California', 'California', 'New York', 'New York', 'Texas', 'Texas'],
    'year': [2000, 2010, 2000, 2010, 2000, 2010],
    'pop': [33.8, 37.2, 18.9, 19.3, 20.8, 25.1]
}
df = pd.DataFrame(data)
df

        state  year   pop
0  California  2000  33.8
1  California  2010  37.2
2    New York  2000  18.9
3    New York  2010  19.3
4       Texas  2000  20.8
5       Texas  2010  25.1

In [100]:
#컬름을 인덱스로 state, year임
df_multi = df.set_index(['state', 'year'])

print(df_multi)

                  pop
state      year
California 2000  33.8
           2010  37.2
New York   2000  18.9
           2010  19.3
Texas      2000  20.8
           2010  25.1

In [101]:
# 현재 pop
pop

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64

In [102]:
index_multi

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           names=['state', 'year'])

In [103]:
pop_multi = pop.reindex(index_multi) #지금있는 index를 버리고 새로운걸(index_multi) 끼워라
#index랑 index_multi의 차이점은 데이터 타입을 다르다
#index역할의 원칙은 index또는 indextype을 해야된다
#기본 index는 list이고 
pop_multi

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [104]:
type(pop_multi)
# pop_multi의 타입은 Series

pandas.Series

In [105]:
# 비효율적인 방법
# pop[[i for i in pop.index if i[1]==2000]] index일때







pop_multi[:, 2000]
#multi_index일때 level 2라 index '2개' 필요 ":"-> 모두다 "2000" -> 2000인 경우만
# pop_multi의 타입은 Series이기 때문에 컬럼이 하나밖에 없음
# pandas는 pop_multi[:, 2000]을 보고 멀티인덱스라고 판단

# pop_multi가 데이터프레임인 경우 pop_multi[:, 2000]는 에러 발생
# df[행, 열]은 없음, df.loc[], df.iloc[]를 사용해야 함

state
California    33871648
New York      18976457
Texas         20851820
dtype: int64

In [106]:
# 정리

import pandas as pd

data = {
    'state': ['California', 'New York', 'Texas', 'Florida'],
    'year': [2000, 2010, 2000, 2010],
    'pop': [33.8, 37.2, 20.8, 18.8]
}
df = pd.DataFrame(data)
df

        state  year   pop
0  California  2000  33.8
1    New York  2010  37.2
2       Texas  2000  20.8
3     Florida  2010  18.8

In [107]:
# 1. df[]는 기본적으로 컬럼 선택 → 컬럼 타입은 대체로 문자열

col_state = df['state'] #대괄호 안에 있는건 컬럼 선택이다
print(col_state)

# 리스트를 넣어서 여러 컬럼 선택
cols = df[['state', 'pop']]
print(cols)

0    California
1      New York
2         Texas
3       Florida
Name: state, dtype: str
        state   pop
0  California  33.8
1    New York  37.2
2       Texas  20.8
3     Florida  18.8

In [108]:
# 2. df[]에 ":"를 사용하면 행 선택

rows = df[0:2]  # 대괄호 안에 ":"를 넣으면 행을 선택을한다 (ex: 0~1까자)
print(rows)

# df[]에 쉼표가 없다
# 1. 슬라이스 → 행 선택
# 2.   컬럼명 → 열 선택, [컬럼1, 컬럼 2, ...]은 쉼표가 아니라 단일 리스트를 넘긴 것

        state  year   pop
0  California  2000  33.8
1    New York  2010  37.2

In [109]:
# 3. 불리언 마스크를 사용하면 행 선택
#불리언 마스크 란? -> ['pop'] 갈럼이 30보다 크다 
mask = df['pop'] > 30
print(df[mask])

        state  year   pop
0  California  2000  33.8
1    New York  2010  37.2

In [110]:
# 컬럼 이름을 알려주지 않음

df = pd.DataFrame([[10, 20], [30, 40]])
# pandas가 디폴트 컬럼 이름 0, 1, 2, ...을 사용
# 이 경우 컬럼명은 숫자 타입에 해당
print(df)
print('-'*100)
print(df[0]) 

# print(df['0']) # KeyError: '0'

    0   1
0  10  20
1  30  40
----------------------------------------------------------------------------------------------------
0    10
1    30
Name: 0, dtype: int64

In [111]:
# pd.Series를 데이터프레임에 끼워넣기

pop_multi

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [112]:
pop_df = pd.DataFrame({
    'total': pop_multi,
    'under18': [9267089, 9284094, 4687374, 4318033, 5906301, 6879014],
})

pop_df

                    total  under18
state      year
California 2000  33871648  9267089
           2010  37253956  9284094
New York   2000  18976457  4687374
           2010  19378102  4318033
Texas      2000  20851820  5906301
           2010  25145561  6879014

In [113]:
# 인덱스 이름 - 다 만들고 나중에 이름 붙이기

rng = np.random.RandomState(42) #random number generator
rng.rand(6, 3) # 6은 행의 갯수 3은 열의 갯수

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452],
       [0.05808361, 0.86617615, 0.60111501],
       [0.70807258, 0.02058449, 0.96990985],
       [0.83244264, 0.21233911, 0.18182497],
       [0.18340451, 0.30424224, 0.52475643]])

In [114]:
# rng.rand(6, 3)는 난수 생성기(rng)를 사용해서 6행 3열의 2차원 배열을 생성
df = pd.DataFrame(rng.rand(6, 3), 
                  index=[['A', 'A', 'B', 'B', 'C', 'C'], [1,2,1,2,1,2]], #멀티 인덱스 생성
                  columns= ['col1', 'col2', 'col3']
                  )
#현재 인덱스 이름이 없다
df

         col1      col2      col3
A 1  0.431945  0.291229  0.611853
  2  0.139494  0.292145  0.366362
B 1  0.456070  0.785176  0.199674
  2  0.514234  0.592415  0.046450
C 1  0.607545  0.170524  0.065052
  2  0.948886  0.965632  0.808397

In [115]:
df.index.names = ['index1', 'index2'] #멀티 인덱스이므로 이름이 2개가 필요하다
df

                   col1      col2      col3
index1 index2
A      1       0.431945  0.291229  0.611853
       2       0.139494  0.292145  0.366362
B      1       0.456070  0.785176  0.199674
       2       0.514234  0.592415  0.046450
C      1       0.607545  0.170524  0.065052
       2       0.948886  0.965632  0.808397

In [116]:
# 인덱스 이름 - 만들면서 알려주기

index_arr = [['A', 'A', 'B', 'B', 'C', 'C'], [1,2,1,2,1,2]]
index = pd.MultiIndex.from_arrays(index_arr, names= ('index1', 'index2'))
#                                            ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑

df = pd.DataFrame(rng.rand(6,3), 
                  index=index,
                  columns= ['col1', 'col2', 'col3']
                  )

df

                   col1      col2      col3
index1 index2
A      1       0.304614  0.097672  0.684233
       2       0.440152  0.122038  0.495177
B      1       0.034389  0.909320  0.258780
       2       0.662522  0.311711  0.520068
C      1       0.546710  0.184854  0.969585
       2       0.775133  0.939499  0.894827

In [117]:
# 행만 있냐? 컬럼도 있다
row_index = pd.MultiIndex.from_product([[2013, 2014], ['1st', '2nd']], names = ['Year', 'Visit'])
col_index = pd.MultiIndex.from_product([['Bob', 'Guido', 'Sue'], ['HR', 'Temp']], names= ['Patient', 'Data type'])
print(row_index)
print(col_index)

MultiIndex([(2013, '1st'),
            (2013, '2nd'),
            (2014, '1st'),
            (2014, '2nd')],
           names=['Year', 'Visit'])
MultiIndex([(  'Bob',   'HR'),
            (  'Bob', 'Temp'),
            ('Guido',   'HR'),
            ('Guido', 'Temp'),
            (  'Sue',   'HR'),
            (  'Sue', 'Temp')],
           names=['Patient', 'Data type'])

In [118]:
data_hr = np.random.randint(50, 80, 12) # 50부터 79까지의 정수중에서 무작위로 12개 선택
data_temp = 37 + np.random.randn(12) # 평균이 0이고 표준편차가 1인 표준정규분포 random number 12개

data_x = [i for i in zip(data_hr, data_temp)]
data_x

[(np.int32(77), np.float64(35.855187071222865)),
 (np.int32(53), np.float64(36.35995019790062)),
 (np.int32(70), np.float64(35.05027836453042)),
 (np.int32(64), np.float64(34.91719706494735)),
 (np.int32(68), np.float64(36.37054684600048)),
 (np.int32(72), np.float64(37.85991463966898)),
 (np.int32(58), np.float64(37.36923634687326)),
 (np.int32(51), np.float64(36.870075862065505)),
 (np.int32(64), np.float64(37.61639809620598)),
 (np.int32(61), np.float64(36.7611836851698)),
 (np.int32(58), np.float64(36.47050811328792)),
 (np.int32(60), np.float64(36.386190959456))]

In [119]:
arr = np.array(data_x)
print(arr.shape)
arr

(12, 2)

array([[77.        , 35.85518707],
       [53.        , 36.3599502 ],
       [70.        , 35.05027836],
       [64.        , 34.91719706],
       [68.        , 36.37054685],
       [72.        , 37.85991464],
       [58.        , 37.36923635],
       [51.        , 36.87007586],
       [64.        , 37.6163981 ],
       [61.        , 36.76118369],
       [58.        , 36.47050811],
       [60.        , 36.38619096]])

In [120]:
# Reshape to 4 rows and 6 cols
# reshape -> 쉐입을 바꿔라
arr_multi = arr.reshape(4,6)
arr_multi

array([[77.        , 35.85518707, 53.        , 36.3599502 , 70.        ,
        35.05027836],
       [64.        , 34.91719706, 68.        , 36.37054685, 72.        ,
        37.85991464],
       [58.        , 37.36923635, 51.        , 36.87007586, 64.        ,
        37.6163981 ],
       [61.        , 36.76118369, 58.        , 36.47050811, 60.        ,
        36.38619096]])

In [121]:
health_data = pd.DataFrame(arr_multi, columns=col_index, index=row_index)
health_data

Patient      Bob            Guido              Sue
Data type     HR       Temp    HR       Temp    HR       Temp
Year Visit
2013 1st    77.0  35.855187  53.0  36.359950  70.0  35.050278
     2nd    64.0  34.917197  68.0  36.370547  72.0  37.859915
2014 1st    58.0  37.369236  51.0  36.870076  64.0  37.616398
     2nd    61.0  36.761184  58.0  36.470508  60.0  36.386191

In [122]:
health_data['Bob']

Data type     HR       Temp
Year Visit
2013 1st    77.0  35.855187
     2nd    64.0  34.917197
2014 1st    58.0  37.369236
     2nd    61.0  36.761184

In [123]:
health_data['Bob']['HR']
#health_data['Bob','HR']

Year  Visit
2013  1st      77.0
      2nd      64.0
2014  1st      58.0
      2nd      61.0
Name: HR, dtype: float64

In [ ]:
health_data.loc[2014, ('Bob','HR')]
# health_data.loc[2014, ['Bob','HR']]
# 튜플로 전달함
# 튜플은 계층을 표현: ('Bob','HR') → 첫 번째 인덱스는 'Bob', 두 번째 인덱스는 'HR'
# 리스트는 단순 나열임 → 첫 번째 인덱스에 'Bob'은 있지만 'HR'는 없음

Visit
1st    58.0
2nd    61.0
Name: (Bob, HR), dtype: float64

In [126]:
health_data.loc[2014,['Bob','Sue']]

Patient     Bob              Sue
Data type    HR       Temp    HR       Temp
Visit
1st        58.0  37.369236  64.0  37.616398
2nd        61.0  36.761184  60.0  36.386191