In [1]:
import pandas as pd

data = {'Name':['John','Alice','Bob'],
        'Age':[22,30,22],
        'Gender':['male','female','male'],
        'Salary':[50000,55000,40000]}
df = pd.DataFrame(data)
df

    Name  Age  Gender  Salary
0   John   22    male   50000
1  Alice   30  female   55000
2    Bob   22    male   40000

In [2]:
df.loc[0]

Name       John
Age          25
Gender     male
Salary    50000
Name: 0, dtype: object

In [4]:
df.iloc[0:1]

   Name  Age Gender  Salary
0  John   25   male   50000

In [6]:
df.iloc[:,0:2]

    Name  Age
0   John   25
1  Alice   30
2    Bob   22

In [10]:
df.loc[(df['Salary']>=50000) & (df['Age']>= 25) , ['Name']]

    Name
0   John
1  Alice

In [12]:
sorted_df = df.sort_values(by='Age')
print(sorted_df)

    Name  Age  Gender  Salary
2    Bob   22    male   40000
0   John   25    male   50000
1  Alice   30  female   55000

In [16]:
sorted_df = df.sort_values(by=['Age', 'Salary'])
print(sorted_df)

    Name  Age  Gender  Salary
2    Bob   22    male   40000
0   John   22    male   50000
1  Alice   30  female   55000