In [1]:
import pandas as pd
import numpy as np

In [2]:
s=pd.Series(["Sam",np.nan,"Tim","Kim"])
s
#백터와이즈 이즈널이다

0    Sam
1    NaN
2    Tim
3    Kim
dtype: object

In [3]:
print(type(np.nan)) #n(ot) a n(umber)
#np.nan은 소숫점이있는 숫자(실수)

<class 'float'>

In [4]:
s.isnull()

0    False
1     True
2    False
3    False
dtype: bool

In [5]:
s.notnull()

0     True
1    False
2     True
3     True
dtype: bool

In [6]:
s[3]=None #3번째위치에 None값을 집어 넣었다
#시리즈는 배열인덱스를 사용하면 몇번째 인덱스를 사용할 수 있다
s.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [7]:
s.dropna()
#dropna -> 결측지를 없애라(떨군다)

0    Sam
2    Tim
dtype: object

In [8]:
s
#inplace는 값이 변경 X

0     Sam
1     NaN
2     Tim
3    None
dtype: object

In [9]:
s.dropna(inplace=True)
#

In [10]:
s

0    Sam
2    Tim
dtype: object

In [11]:
print(pd.NA) #pd는 pandas에서 만든거임
#NaT를 제외한 모든것
print(pd.NaT)#날짜 시간의 결측치

<NA>
NaT

In [12]:
# 1
df1 = pd.DataFrame([[1, 2, 3], [4, np.nan, 5], [np.nan, np.nan, np.nan]])

In [13]:
df1.dtypes

0    float64
1    float64
2    float64
dtype: object

In [14]:
# np.nan은 숫자이기 때문에 float 타입의 컬럼에서 그대로 있음
df1

     0    1    2
0  1.0  2.0  3.0
1  4.0  NaN  5.0
2  NaN  NaN  NaN

In [15]:
# 2
df2 = pd.DataFrame([[1.0, 2.0], [None, 4.0]]) #list는 행단위로 넘김

In [16]:
df2.dtypes

0    float64
1    float64
dtype: object

In [17]:
# None은 숫자가 아니기 때문에 float 타입의 컬럼에서 np.nan으로 변환
df2

     0    1
0  1.0  2.0
1  NaN  4.0

In [18]:
# 3

# 차이는 dtype="Int64"으로 타입을 정했는지의 여부
df3 = pd.DataFrame({"a": [1, None, 3]})
df4 = pd.DataFrame({"a": pd.Series([1, None, 3], dtype="Int64")})

In [19]:
df3

     a
0  1.0
1  NaN
2  3.0

In [20]:
df4

      a
0     1
1  <NA>
2     3

In [21]:
# 4
# NA를 사용한 이유

df5 = pd.DataFrame({"a": [1, None, 3]}) 
# 값 [1, None, 3]은 None을 np.nan으로 바꾸기만 하면 float64이 되네?
# None → np.nan이 되면서 원래는 정수였던 1, 3까지도 실수 타입으로 바뀌어 버림

print(df5.dtypes)

a    float64
dtype: object

In [22]:
df6 = pd.DataFrame({"a": pd.array([1, None, 3], dtype="Int64")})
# 값 1, 3은 정수라고 명시적으로 알림
# 이 경우 None은 np.nan이 아닌 pd.NA로 변환

In [23]:
df6

      a
0     1
1  <NA>
2     3

In [24]:
# 정리하면
# 결측치는 세 종류
# 1. 실수(float) → np.nan
# 2. 정수(Int64) → pd.NA
# 3. 날짜/시간 → pd.NaT

# 문자열의 경우도 pd.NA

df = pd.DataFrame({"a": pd.array(["hello", None, "world"], dtype="string")})
df

       a
0  hello
1   <NA>
2  world

In [ ]:

df=pd.DataFrame([[1,2,3],[4, np.nan, 5],
                 [np.nan, np.nan, np.nan]])
df

In [ ]:
df.dtypes

In [ ]:
df.dropna() # ---------- 대상은 np.nan, pd.NA, pd.NaT

In [ ]:
df.dropna(how="all")
# how="any" (디폴트) → 행에 하나라도 결측치가 있으면 제거
# how="all" → 행의 모든 값이 결측치일 때만 제거

In [ ]:
df.fillna(0,inplace=True)
#fillna(값) 결측지를 값으로 채운다
df

In [ ]:
df=pd.DataFrame([[1, 2, 3],[4, pd.NA, 5],
                 [pd.NA, pd.NA, pd.NA]])
df

In [ ]:
df.fillna(0)

In [ ]:
df = pd.DataFrame({
    "실수": [1.0, np.nan, 3.0],
    "정수": pd.array([1, None, 3], dtype="Int64"),
    "날짜": pd.to_datetime(["2024-01-01", None, "2024-01-03"]),
    "문자": pd.array(["hello", None, "world"], dtype="string"),
})

In [ ]:
df

In [ ]:
df.dropna()

In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "a": [1.0, np.nan, np.nan, 4.0],
    "b": [2.0, np.nan, 3.0,   np.nan],
    "c": [3.0, np.nan, 4.0,   5.0],
})
print(df)

In [ ]:

# 1. how="any" (디폴트) → 하나라도 결측치면 제거
df.dropna(how="any")

In [ ]:

# 2. how="all" → 모두 결측치일 때만 제거
df.dropna(how="all")

In [ ]:
# 3. thresh=2 → 결측치가 아닌 값이 2개 이상인 행만 유지
# threshold -> 임계치
df.dropna(thresh=2)

In [ ]:
# 4. subset → 특정 컬럼만 기준으로 삼기
# a 컬럼 기준, a가 NaN인 행만 제거
# subaet ->  부분집합
df.dropna(subset=["a"])

In [ ]:
df

In [ ]:
# 5. axis=1 → 행이 아닌 열 기준으로 제거
df.dropna(axis=0, how="any")
#2차원은 shape이 2개임

In [ ]:
import pandas as pd

data = {
    'Math':[90,80],
    'English':[85,95],
    'Science':[70,75]
}

df = pd.DataFrame(data, index= ['Student_a','Student_b'])
print(df)

In [ ]:
#과목별 총점 
col_sum = df.sum(axis=0)
print(col_sum)

In [ ]:
#학생별 전과목 총점
row_sum = df.sum(axis=1)
print(row_sum)

In [ ]:
import pandas as pd
import numpy as np 

data = {
    'A':[1,2,np.nan],
    'B':[4,np.nan,np.nan],
    'C':[7,8,9]
}

df = pd.DataFrame(data, index=['Row1','Row2','Row3'])
print(df)

In [ ]:
#각 열(column)별 데이터 개수
count_col = df.count(axis=0)
print(count_col)

In [ ]:
#각 행(Row)별 데이터 개수
count_row = df.count(axis=1)
print(count_row)

In [ ]:
import pandas as pd
import numpy as np 

data = {
    'Math':[90,np.nan,80],
    'English':[80,70,np.nan],
    'Science':[100,100,100]
}

df = pd.DataFrame(data, index= ['Student_a','Student_b','Student_c'])
print(df)

In [ ]:
#과목별 평균 (수학 2명의 평균 , 영어도 2명의 평균)
mean_by_subject = df.mean(axis=0)
print(mean_by_subject)

In [ ]:
#학생별평균 본인이 응시한 과복의 평균
mean_by_student =df.mean(axis=1)
print(mean_by_student)

In [ ]:
#min, max 과목별
min_subject = df.min(axis=0)
print(min_subject)
print("--------------------------------------------")
max_subject = df.max(axis=0)
print(max_subject)

In [ ]:
##min, max 학생별
min_student = df.min(axis=1)
print(min_student)
print("--------------------------------------------")
max_student = df.max(axis=1)
print(max_student)